linters-settings:
    golint:
        min-confidence: 0.1
    goimports:
        local-prefixes: logur.dev/logur

linters:
    enable-all: true
    disable:
        - funlen
        - wsl
        - gomnd

        - rowserrcheck
